default: &default
  adapter: mysql2
  host: localhost
  encoding: utf8
  secure_auth: false
  username: rails_user
  password: 'password'

development:
  <<: *default
  database: task_manager

test:
  <<: *default
  database: task_manager_test

production:
  <<: *default
  database: task_manager_prod
