ruby_version: ruby-2.3.0
bundler_version: 1.12.2

postgresql:
  version: '9.3'
  
plan:
- default
- second
- third

profiles:
  default:
    input:
      - build-artifacts-name
    test_pattern:
      - spec/controllers/projects_controller_spec.rb
    output:
      - build-artifacts-name-1
  second:
    input:
      - build-artifacts-name-1
    test_pattern:
      - spec/controllers/projects_controller_spec.rb
    output:
     - build-artifacts-name-2
  third:
    input:
     - build-artifacts-name-2
    test_pattern:
      - spec/controllers/tasks_controller_spec.rb
